FROM node:10

WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package*.json /usr/src/app/
COPY . /usr/src/app/

RUN npm install --silent
RUN npm install react-scripts@3.0.1 -g --silent
RUN npm run build

EXPOSE 3000

CMD ["npm","start"]


