FROM python:3.7

RUN apt update
RUN apt install -y python3-dev gcc


WORKDIR /usr/src/server

ADD requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY . .

EXPOSE 8899

RUN mkdir static
RUN mkdir static/models
RUN python server.py serve &

CMD ["python","server.py","serve"]


